"use client";
/* React Hook Form intentionally manages mutable form state outside React Compiler memoization. */
/* eslint-disable react-hooks/incompatible-library */

import { useEffect, useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Check, ChevronLeft, Minus, Plus, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { calculateDialedScore, roastAgeDays } from "@/lib/calculations";
import { formatRatio } from "@/lib/formatting";
import { shotSchema, type ShotInput } from "@/lib/validation";
import { removeShotDraft, readShotDraft, writeShotDraft } from "@/lib/shot-draft";
import { useOnlineStatus } from "@/hooks/use-online-status";
import { saveShot } from "@/features/data/actions";
import type { Bean, Equipment, Shot, UserSettings } from "@/types/domain";

const tastes = [["very_sour", "🍋", "Sehr sauer"], ["sour", "◐", "Leicht sauer"], ["balanced", "●", "Balanciert"], ["bitter", "◑", "Leicht bitter"], ["very_bitter", "◆", "Sehr bitter"]] as const;
const flows = [["even", "Gleichmäßig", "Ruhiger, mittiger Flow"], ["minor_channeling", "Leichtes Channeling", "Unruhig oder leicht seitlich"], ["channeling", "Starkes Channeling", "Mehrere schnelle Kanäle"], ["spritzing", "Spritzing", "Deutliche seitliche Spritzer"]] as const;
const pucks = [["dry", "Zu trocken", "Rissig oder sehr hart"], ["ideal", "Sauber & stabil", "Normal feucht, kompakt"], ["wet", "Sehr nass", "Wasser steht auf dem Puck"], ["stuck", "Hängengeblieben", "Am Duschsieb festgeklebt"]] as const;
const timerStorageKey = (userId: string) => `dialed:shot-timer:${userId}`;
const MAX_RESTORED_TIMER_MS = 30 * 60 * 1000;

export function ShotWizard({ userId, beans, equipment, settings, lastShot }: { userId: string; beans: Bean[]; equipment: Equipment[]; settings: UserSettings | null; lastShot: Shot | null }) {
  const router = useRouter();
  const isOnline = useOnlineStatus();
  const [pending, startTransition] = useTransition();
  const [step, setStep] = useState<1 | 2 | 3>(1);
  const [draftReady, setDraftReady] = useState(false);
  const [running, setRunning] = useState(false);
  const [elapsed, setElapsed] = useState(0);
  const baseRef = useRef(0);
  const startedAtRef = useRef(0);
  const frameRef = useRef(0);
  const activeBeans = beans.filter((bean) => !bean.archived_at);
  const machines = equipment.filter((item) => item.type === "machine" && !item.archived_at);
  const grinders = equipment.filter((item) => item.type === "grinder" && !item.archived_at);
  const defaultBean = activeBeans.find((bean) => bean.id === settings?.last_bean_id) ?? activeBeans[0];
  const { register, watch, setValue, trigger, handleSubmit, reset, formState: { errors } } = useForm<ShotInput>({
    resolver: zodResolver(shotSchema),
    defaultValues: {
      beanId: defaultBean?.id ?? "", machineId: settings?.auto_fill ? settings.default_machine_id : null, grinderId: settings?.auto_fill ? settings.default_grinder_id : null, basketId: null,
      grindSetting: lastShot?.grind_setting ?? null, doseGrams: lastShot?.dose_grams ?? null, temperatureC: lastShot?.temperature_c ?? null, preinfusionSeconds: null, prepTools: settings?.default_prep_tools ?? null,
      extractionSeconds: lastShot?.extraction_seconds ?? null, stopWeightGrams: lastShot?.stop_weight_grams ?? null, finalYieldGrams: lastShot?.final_yield_grams ?? null, taste: lastShot?.taste ?? null, flow: lastShot?.flow ?? null, puck: lastShot?.puck ?? null, notes: lastShot?.notes ?? null,
      overallTasteRating: lastShot?.overall_taste_rating ?? null, tds: lastShot?.tds ?? null, flowEvenness: lastShot?.flow_evenness ?? null, channeling: lastShot?.channeling ?? null,
    },
  });
  const values = watch();
  const scoreResult = calculateDialedScore({ doseGrams: values.doseGrams, finalYieldGrams: values.finalYieldGrams, extractionSeconds: values.extractionSeconds, overallTasteRating: values.overallTasteRating, tasteBalance: values.taste, flow: values.flow, puck: values.puck, flowEvenness: values.flowEvenness, channeling: values.channeling, tds: values.tds });

  useEffect(() => { const draft = readShotDraft(userId); if (draft) { let restoredElapsed = draft.values.extractionSeconds ? draft.values.extractionSeconds * 1000 : 0; reset(draft.values); setStep(draft.step); try { const timer = JSON.parse(window.localStorage.getItem(timerStorageKey(userId)) ?? "null") as { startedAt?: number; baseMs?: number } | null; if (timer?.startedAt && typeof timer.baseMs === "number") { const liveElapsed = timer.baseMs + Date.now() - timer.startedAt; if (liveElapsed > 0 && liveElapsed <= MAX_RESTORED_TIMER_MS) { restoredElapsed = liveElapsed; baseRef.current = timer.baseMs; startedAtRef.current = timer.startedAt; setRunning(true); setValue("extractionSeconds", liveElapsed / 1000, { shouldValidate: false }); } else window.localStorage.removeItem(timerStorageKey(userId)); } } catch { window.localStorage.removeItem(timerStorageKey(userId)); } setElapsed(restoredElapsed); if (!startedAtRef.current) baseRef.current = restoredElapsed; toast.info("Shot-Entwurf fortgesetzt", { id: "shot-draft-restored" }); } setDraftReady(true); }, [reset, setValue, userId]);
  useEffect(() => { if (!draftReady) return; const timer = window.setTimeout(() => writeShotDraft(userId, step, values), 350); return () => window.clearTimeout(timer); }, [draftReady, step, userId, values]);
  useEffect(() => { if (!draftReady) return; const preserve = () => writeShotDraft(userId, step, values); window.addEventListener("pagehide", preserve); return () => window.removeEventListener("pagehide", preserve); }, [draftReady, step, userId, values]);
  useEffect(() => { if (!running) return; const tick = () => { const next = baseRef.current + Date.now() - startedAtRef.current; setElapsed(next); setValue("extractionSeconds", Math.max(0.1, next / 1000), { shouldValidate: false }); frameRef.current = requestAnimationFrame(tick); }; frameRef.current = requestAnimationFrame(tick); return () => cancelAnimationFrame(frameRef.current); }, [running, setValue]);

  const toggleTimer = () => { if (running) { baseRef.current = elapsed; setRunning(false); window.localStorage.removeItem(timerStorageKey(userId)); } else { startedAtRef.current = Date.now(); window.localStorage.setItem(timerStorageKey(userId), JSON.stringify({ startedAt: startedAtRef.current, baseMs: baseRef.current })); setRunning(true); } };
  const resetTimer = () => { setRunning(false); baseRef.current = 0; startedAtRef.current = 0; setElapsed(0); setValue("extractionSeconds", null); window.localStorage.removeItem(timerStorageKey(userId)); };
  const close = () => { writeShotDraft(userId, step, values); toast.success("Shot als Entwurf gespeichert", { description: "Du kannst ihn unter Shots weiter bearbeiten." }); router.push("/app/shots"); };
  const next = async () => { if (step === 1) { if (await trigger(["beanId"])) setStep(2); } else { if (running) { baseRef.current = elapsed; setRunning(false); window.localStorage.removeItem(timerStorageKey(userId)); } setStep(3); } };
  const submit = (data: ShotInput) => { if (!isOnline) { writeShotDraft(userId, step, data); toast.error("Offline gespeichert", { description: "Der Entwurf bleibt auf diesem Gerät. Speichere den Shot, sobald du wieder online bist." }); return; } startTransition(async () => { const result = await saveShot(data); if (!result.ok) { toast.error(result.message); return; } window.localStorage.removeItem(timerStorageKey(userId)); removeShotDraft(userId); toast.success("Shot gespeichert", { description: result.message }); router.push("/app"); router.refresh(); }); };
  const timerText = `${String(Math.floor(elapsed / 60000)).padStart(2, "0")}:${String(Math.floor(elapsed / 1000) % 60).padStart(2, "0")}.${Math.floor(elapsed / 100) % 10}`;
  const ratio = values.doseGrams && values.finalYieldGrams ? formatRatio(values.finalYieldGrams / values.doseGrams) : "—";

  return <div className="fixed inset-0 z-50 grid bg-[var(--dialed-surface)] min-[561px]:absolute">
    <header className="border-b bg-[rgba(251,248,243,.95)] px-[18px] pt-[calc(16px+env(safe-area-inset-top))] pb-3 backdrop-blur"><div className="grid grid-cols-[40px_1fr_40px] items-center"><button type="button" onClick={close} aria-label="Schließen" className="grid size-[38px] place-items-center rounded-full bg-[var(--dialed-surface-subtle)]"><X className="size-[18px]" /></button><h1 className="text-center font-display text-[22px]">Neuer Shot</h1></div><div className="mt-3.5 grid grid-cols-3 gap-1.5">{[1, 2, 3].map((item) => <span key={item} className={`h-1 rounded-full ${item <= step ? "bg-[var(--dialed-crema)]" : "bg-[var(--dialed-surface-strong)]"}`} />)}</div><div className="mt-1.5 grid grid-cols-3 text-center text-[8px] text-[var(--dialed-text-muted)]">{["Setup", "Extraktion", "Review"].map((label, index) => <span key={label} className={step === index + 1 ? "font-extrabold text-[var(--dialed-text)]" : ""}>{label}</span>)}</div></header>
    <form onSubmit={handleSubmit(submit)} className="grid min-h-0 grid-rows-[minmax(0,1fr)_auto]">
      <div className="scrollbar-none min-h-0 overflow-y-auto px-[18px] py-[19px] pb-6"><div className="mx-auto max-w-[680px]">
        {step === 1 && <><Intro title="Was kommt in den Siebträger?">Fehlende Werte bleiben offen und werden nicht geschätzt.</Intro><Section title="Mahlgrad & Dosis"><div className="space-y-2"><Label>Mahlgrad optional</Label><div className="grid grid-cols-[46px_1fr_46px] gap-2"><button type="button" onClick={() => setValue("grindSetting", ((Number(values.grindSetting) || 0) - 0.1).toFixed(1))} className="grid h-12 place-items-center rounded-[13px] bg-[var(--dialed-surface-subtle)]"><Minus className="size-4" /></button><Input className="h-12 text-center font-bold" {...register("grindSetting")} /><button type="button" onClick={() => setValue("grindSetting", ((Number(values.grindSetting) || 0) + 0.1).toFixed(1))} className="grid h-12 place-items-center rounded-[13px] bg-[var(--dialed-surface-subtle)]"><Plus className="size-4" /></button></div></div><div className="mt-3 grid grid-cols-2 gap-2"><NumberField label="Dosis optional" unit="g" registration={register("doseGrams", { setValueAs: (value) => value === "" ? null : Number(value) })} /><NumberField label="Temperatur optional" unit="°C" registration={register("temperatureC", { setValueAs: (value) => value === "" ? null : Number(value) })} /></div></Section><Section title="Puck Prep"><div className="grid grid-cols-2 gap-2">{["WDT", "Tamper", "Puck Screen", "Leveler"].map((tool) => { const active = (values.prepTools ?? []).includes(tool); return <button type="button" key={tool} aria-pressed={active} onClick={() => setValue("prepTools", active ? (values.prepTools ?? []).filter((item) => item !== tool) : [...(values.prepTools ?? []), tool])} className={`flex min-h-[70px] flex-col justify-between rounded-[14px] border p-3 text-left text-[10px] font-bold ${active ? "border-[var(--dialed-sage)]/30 bg-[var(--dialed-sage-soft)]" : "bg-[var(--dialed-surface)]"}`}><Check className={`size-4 text-[var(--dialed-sage)] ${active ? "" : "opacity-0"}`} />{tool}</button>; })}</div></Section><Section title="Bohne"><select aria-label="Bohne wählen" className="h-14 w-full rounded-[18px] border bg-white px-3 text-xs" {...register("beanId")}>{activeBeans.map((bean) => <option key={bean.id} value={bean.id}>{bean.name} · {bean.roaster}{bean.roast_date ? ` · ${roastAgeDays(bean.roast_date)} Tage` : ""}</option>)}</select><Error text={errors.beanId?.message} /></Section><Section title="Equipment"><SelectField label="Maschine" options={machines} registration={register("machineId")} /><SelectField label="Mühle" options={grinders} registration={register("grinderId")} /></Section></>}
        {step === 2 && <><Intro title="Extraktion läuft.">Trage nur Werte ein, die du wirklich gemessen hast.</Intro><div className="py-1 text-center"><div className="relative mx-auto mb-4 grid size-[204px] place-items-center rounded-full p-2.5 shadow-[0_18px_40px_rgba(54,34,24,.1)]" style={{ background: `conic-gradient(var(--dialed-crema) ${Math.min(100, elapsed / 400)}%,var(--dialed-surface-strong) 0)` }}><div className="grid size-full place-items-center rounded-full border bg-[var(--dialed-surface)]"><div><small className="mb-2 block text-[8px] uppercase tracking-[.12em] text-[var(--dialed-text-muted)]">Extraktionszeit</small><strong className="font-mono text-[42px] tracking-[-.07em]">{timerText}</strong></div></div></div><div className="flex justify-center gap-2"><Button type="button" onClick={toggleTimer} className={`h-11 rounded-full ${running ? "bg-[var(--dialed-rose)]" : "bg-[var(--dialed-espresso)]"}`}>{running ? "Timer stoppen" : elapsed ? "Weiterlaufen" : "Timer starten"}</Button><Button type="button" variant="secondary" onClick={resetTimer} className="h-11 rounded-full">Zurücksetzen</Button></div></div><div className="my-3 flex items-center justify-between rounded-[18px] bg-[var(--dialed-espresso)] p-4 text-white"><span className="text-[10px] text-white/60">Aktuelles Brew Ratio</span><strong className="font-display text-2xl">{ratio}</strong></div><Section><div className="grid grid-cols-2 gap-2"><div className="col-span-2"><NumberField label="Zeit optional" unit="s" registration={register("extractionSeconds", { setValueAs: (value) => value === "" ? null : Number(value) })} /></div><NumberField label="Stop-Gewicht optional" unit="g" registration={register("stopWeightGrams", { setValueAs: (value) => value === "" ? null : Number(value) })} /><NumberField label="Finales Gewicht optional" unit="g" registration={register("finalYieldGrams", { setValueAs: (value) => value === "" ? null : Number(value) })} /></div><Error text={errors.finalYieldGrams?.message} /></Section></>}
        {step === 3 && <><Intro title="Wie war der Shot?">Der Score wird nur berechnet, wenn die Mindestdaten vorhanden sind.</Intro><div className="mb-3 flex items-center gap-3 rounded-[24px] bg-[linear-gradient(135deg,var(--dialed-espresso),var(--dialed-espresso-raised))] p-4 text-white"><div className="grid size-[58px] place-items-center rounded-full bg-white/10 font-display text-2xl">{scoreResult.score ?? "—"}</div><div><strong className="text-xs">Dialed Score</strong><p className="mt-1 text-[9px] text-white/60">Datenabdeckung: {scoreResult.coverage}% · {scoreResult.coverageLabel}</p></div></div><Section title="Geschmack" meta="Sauer → Bitter"><div className="grid grid-cols-5 gap-1.5">{tastes.map(([id, icon, label]) => <button type="button" key={id} onClick={() => setValue("taste", id)} aria-pressed={values.taste === id} className={`grid min-h-[82px] place-items-center rounded-[14px] border px-1 text-center ${values.taste === id ? "-translate-y-0.5 border-[var(--dialed-crema)] bg-[var(--dialed-crema-soft)]" : "bg-[var(--dialed-surface)]"}`}><span className="text-lg">{icon}</span><span className="text-[8px] leading-tight">{label}</span></button>)}</div></Section><ChoiceSection title="Flow" values={flows} active={values.flow} onSelect={(value) => setValue("flow", value)} /><ChoiceSection title="Puck" values={pucks} active={values.puck} onSelect={(value) => setValue("puck", value)} /><Section><Label htmlFor="notes">Notiz optional</Label><Textarea id="notes" className="mt-2 min-h-24" {...register("notes")} /></Section></>}
      </div></div>
      <footer className="flex gap-2.5 border-t bg-[rgba(251,248,243,.94)] px-[18px] pt-3 pb-[calc(14px+env(safe-area-inset-bottom))] backdrop-blur"><Button type="button" variant="secondary" onClick={() => setStep((current) => Math.max(1, current - 1) as 1 | 2 | 3)} className={`h-12 flex-1 rounded-full ${step === 1 ? "invisible" : ""}`}><ChevronLeft />Zurück</Button>{step < 3 ? <Button key={`next-${step}`} type="button" onClick={(event) => { event.preventDefault(); void next(); }} className="h-12 flex-1 rounded-full bg-[var(--dialed-crema)] text-[var(--dialed-text)]">Weiter</Button> : <Button type="submit" disabled={pending || !isOnline} className="h-12 flex-1 rounded-full bg-[var(--dialed-crema)] text-[var(--dialed-text)]">{pending ? "Speichert …" : isOnline ? "Review abschließen & speichern" : "Offline – Entwurf bleibt erhalten"}</Button>}</footer>
    </form>
  </div>;
}

function Intro({ title, children }: { title: string; children: React.ReactNode }) { return <div className="mb-[18px]"><h2 className="font-display text-[25px] font-medium">{title}</h2><p className="mt-1.5 text-[11px] leading-4 text-[var(--dialed-text-muted)]">{children}</p></div>; }
function Section({ title, meta, children }: { title?: string; meta?: string; children: React.ReactNode }) { return <section className="mb-3 rounded-[24px] border bg-white p-4">{title && <div className="mb-3 flex justify-between"><strong className="text-xs">{title}</strong>{meta && <span className="text-[9px] text-[var(--dialed-text-muted)]">{meta}</span>}</div>}{children}</section>; }
function NumberField({ label, unit, registration }: { label: string; unit: string; registration: ReturnType<ReturnType<typeof useForm<ShotInput>>["register"]> }) { return <div><Label className="mb-1.5 ml-1 block text-[9px] text-[var(--dialed-text-muted)]">{label}</Label><div className="flex h-12 items-center rounded-[13px] bg-[var(--dialed-surface-subtle)] px-3"><input type="number" step="0.1" className="w-full bg-transparent text-xs outline-none" {...registration} /><span className="text-[10px] text-[var(--dialed-text-muted)]">{unit}</span></div></div>; }
function SelectField({ label, options, registration }: { label: string; options: Equipment[]; registration: ReturnType<ReturnType<typeof useForm<ShotInput>>["register"]> }) { return <label className="mt-2 flex min-h-14 items-center gap-3 rounded-[18px] border p-3"><span className="grid size-10 place-items-center rounded-[13px] bg-[var(--dialed-surface-subtle)]">☕</span><span className="min-w-0 flex-1"><small className="block text-[9px] text-[var(--dialed-text-muted)]">{label}</small><select className="w-full bg-transparent text-xs font-bold outline-none" {...registration}><option value="">Nicht gewählt</option>{options.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></span></label>; }
function ChoiceSection<T extends string>({ title, values, active, onSelect }: { title: string; values: readonly (readonly [T, string, string])[]; active: T | null; onSelect: (value: T) => void }) { return <Section title={title}><div className="grid grid-cols-2 gap-2">{values.map(([id, label, copy]) => <button type="button" key={id} onClick={() => onSelect(id)} aria-pressed={active === id} className={`min-h-[84px] rounded-[14px] border p-3 text-left ${active === id ? "border-[var(--dialed-sage)]/30 bg-[var(--dialed-sage-soft)]" : "bg-[var(--dialed-surface)]"}`}><strong className="block text-[10px]">{label}</strong><span className="mt-1 block text-[8px] leading-3 text-[var(--dialed-text-muted)]">{copy}</span></button>)}</div></Section>; }
function Error({ text }: { text?: string }) { return text ? <p role="alert" className="mt-2 text-[10px] text-[var(--dialed-rose)]">{text}</p> : null; }
